In [246]:
# Second task: a classification excercise
#
# Common imports
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt

In [247]:
import sklearn

In [248]:
# Get the dataset from scikitlearn library
from sklearn import datasets

iris = datasets.load_iris()

print(iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [249]:
# We first want to train the simpliest binary classifier for Iris virginica. This classifier has two output classes, it's a Iris virginica
# or it's not a Iris virginica. In other words, the answer to the question "Is it a five digit?" can be True (1) or False (0).
# Moreover, I use only one feature (petal width) from the dataset.

X = iris["data"][:, (2, 3)]  # petal length, petal width
y = iris["target"]   

In [250]:
print(X)

[[1.4 0.2]
 [1.4 0.2]
 [1.3 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [1.7 0.4]
 [1.4 0.3]
 [1.5 0.2]
 [1.4 0.2]
 [1.5 0.1]
 [1.5 0.2]
 [1.6 0.2]
 [1.4 0.1]
 [1.1 0.1]
 [1.2 0.2]
 [1.5 0.4]
 [1.3 0.4]
 [1.4 0.3]
 [1.7 0.3]
 [1.5 0.3]
 [1.7 0.2]
 [1.5 0.4]
 [1.  0.2]
 [1.7 0.5]
 [1.9 0.2]
 [1.6 0.2]
 [1.6 0.4]
 [1.5 0.2]
 [1.4 0.2]
 [1.6 0.2]
 [1.6 0.2]
 [1.5 0.4]
 [1.5 0.1]
 [1.4 0.2]
 [1.5 0.2]
 [1.2 0.2]
 [1.3 0.2]
 [1.4 0.1]
 [1.3 0.2]
 [1.5 0.2]
 [1.3 0.3]
 [1.3 0.3]
 [1.3 0.2]
 [1.6 0.6]
 [1.9 0.4]
 [1.4 0.3]
 [1.6 0.2]
 [1.4 0.2]
 [1.5 0.2]
 [1.4 0.2]
 [4.7 1.4]
 [4.5 1.5]
 [4.9 1.5]
 [4.  1.3]
 [4.6 1.5]
 [4.5 1.3]
 [4.7 1.6]
 [3.3 1. ]
 [4.6 1.3]
 [3.9 1.4]
 [3.5 1. ]
 [4.2 1.5]
 [4.  1. ]
 [4.7 1.4]
 [3.6 1.3]
 [4.4 1.4]
 [4.5 1.5]
 [4.1 1. ]
 [4.5 1.5]
 [3.9 1.1]
 [4.8 1.8]
 [4.  1.3]
 [4.9 1.5]
 [4.7 1.2]
 [4.3 1.3]
 [4.4 1.4]
 [4.8 1.4]
 [5.  1.7]
 [4.5 1.5]
 [3.5 1. ]
 [3.8 1.1]
 [3.7 1. ]
 [3.9 1.2]
 [5.1 1.6]
 [4.5 1.5]
 [4.5 1.6]
 [4.7 1.5]
 [4.4 1.3]
 [4.1 1.3]
 [4.  1.3]
 [4.4 1.2]

In [251]:
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [252]:
# I can now train a Softmax classifier, also known a multinomial classifier (remember what we discussed during the lectures)...
# A softmax classifier in scikit learn is a LogisticRegression with multi_class="multinomial" as parameter
from sklearn.linear_model import LogisticRegression

softmax_reg = LogisticRegression(multi_class="multinomial", random_state=42)  # C here is a regularization parameter
softmax_reg.fit(X, y)

/home/ale/.local/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:1272: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.8. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='multinomial', random_state=42)

In [253]:
# An alternative way (and maybe simplier for a single value) to do it is:
y_new = softmax_reg.predict([[1.0, 0.5]])    # petal length 1.0, petal width 0.5
y_new

array([0])

In [254]:
#TODO: Predict the class for another couple of values of petal length and width
y_new_1 = softmax_reg.predict([[4.0, 1]])    # petal length 1.0, petal width 0.5
y_new_1

array([1])

In [255]:
# As for a binary classifier, we can also compute the probabilities. This time, I'll get one prob. value for each class
y_proba = softmax_reg.predict_proba([[1.0, 0.5]])
y_proba

array([[9.92867108e-01, 7.13288230e-03, 9.75251823e-09]])

In [256]:
#TODO: Calculate the probabilities for another couple of values of petal length and width
y_proba_1 = softmax_reg.predict_proba([[4.0, 1]])
y_proba_1

array([[0.02404399, 0.96249222, 0.01346379]])

In [257]:
# Now let's try to compute the confusion matrix for this classifier. We do it on the whole dataset
# (not very correct) because the dataset is small (we should use cross validation, but it is more complicated)

y_pred = softmax_reg.predict(X)

from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred)

array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  2, 48]])

In [258]:
# We can compute other scores, as precision and recall
# Note: for multiclass classifiers, we need to set the "average" parameter. If None, it calculates the score for each class.
# Other options are possible (see https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_score.html)

from sklearn.metrics import precision_score, recall_score

precision_score(y, y_pred, average=None)

array([1.        , 0.95918367, 0.94117647])

In [259]:
recall_score(y, y_pred, average=None)

array([1.  , 0.94, 0.96])

In [260]:
#TODO: Now train a Random Forest multiclass classifier on the iris set, using all features available (sepal length and width, 
# petal length and width). 
# Use the RandomForestClassifier from scikit learn library. Set as n_estimators=500 and all other hyperparameters with 
# default values.
# After training, calculate the confusion matrix and scores for this classifier. Compare the results with the
# softmax classifier. Try another value of n_estimators.

from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

rf_reg1 = RandomForestClassifier(n_estimators= 500, random_state=42)
rf_reg2 = RandomForestClassifier(n_estimators= 10, random_state=42) # 10 has been obtained by searching the minimum value necessary to obtain the same result as the n_estimator = 500 case
softmax_reg = LogisticRegression(random_state=42, max_iter=1000)  # C here is a regularization parameter

X = iris["data"]  # all the features
y = iris["target"]  

rf_reg1.fit(X, y)
rf_reg2.fit(X, y)
softmax_reg.fit(X, y)

y_pred_rf1 = rf_reg1.predict(X)
y_pred_rf2 = rf_reg2.predict(X)
y_pred_sftmax = softmax_reg.predict(X)

conf_matrix_rf1 = confusion_matrix(y, y_pred_rf1)
prec_score_rf1 = precision_score(y, y_pred_rf1, average=None)
recall_score_rf1 = recall_score(y, y_pred_rf1, average=None)

conf_matrix_rf2 = confusion_matrix(y, y_pred_rf2)
prec_score_rf2 = precision_score(y, y_pred_rf2, average=None)
recall_score_rf2 = recall_score(y, y_pred_rf2, average=None)

conf_matrix_sftmax = confusion_matrix(y, y_pred_sftmax)
prec_score_sftmax = precision_score(y, y_pred_sftmax, average=None)
recall_score_sftmax = recall_score(y, y_pred_sftmax, average=None)


print(f"{conf_matrix_rf1 = }")
print(f"{prec_score_rf1 = }")
print(f"{recall_score_rf1 = }")
print(f"{conf_matrix_rf2 = }")
print(f"{prec_score_rf2 = }")
print(f"{recall_score_rf2 = }")
print(f"{conf_matrix_sftmax = }")
print(f"{prec_score_sftmax = }")
print(f"{recall_score_sftmax = }")


conf_matrix_rf1 = array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]])
prec_score_rf1 = array([1., 1., 1.])
recall_score_rf1 = array([1., 1., 1.])
conf_matrix_rf2 = array([[50,  0,  0],
       [ 0, 50,  0],
       [ 0,  0, 50]])
prec_score_rf2 = array([1., 1., 1.])
recall_score_rf2 = array([1., 1., 1.])
conf_matrix_sftmax = array([[50,  0,  0],
       [ 0, 47,  3],
       [ 0,  1, 49]])
prec_score_sftmax = array([1.        , 0.97916667, 0.94230769])
recall_score_sftmax = array([1.  , 0.94, 0.98])


In [261]:
#TODO: One great advantage of Random Forests is that they can tell you the relative importance of the features. 
# Try to get it from the classifier you just trained. It is an attribute of the classifier called "feature_importances_".
# If your classifier name is "randfor_clf", then the feature importance values are in "randfor_clf.feature_importances_".
# Which is the most important feature for this classifier?

print(rf_reg1.feature_importances_)
print(rf_reg2.feature_importances_)

[0.11249225 0.02311929 0.44103046 0.423358  ]
[0.1292683  0.01582194 0.4447404  0.41016935]


In [262]:
#TODO: Reload the iris dataset and retrain a softmax and a random forest multiclass classifier, 
# but this time first of all split the dataset into a training set and test set as in example 1. 
# Then do the training of the training set only and calculate the scores and confusion matrix 
# on both the training and test sets. Compare the results.

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

rf_reg1 = RandomForestClassifier(n_estimators= 500, random_state=42)
rf_reg2 = RandomForestClassifier(n_estimators= 10, random_state=42) # 10 has been obtained by searching the minimum value necessary to obtain the same result as the n_estimator = 500 case

X = iris["data"]  # all the features
y = iris["target"]  
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify = y) # we divide in test and train sets

rf_reg1.fit(X_train, y_train)
rf_reg2.fit(X_train, y_train)

y_pred_rf1_train = rf_reg1.predict(X_train)
y_pred_rf1_test = rf_reg1.predict(X_test)
y_pred_rf2_train = rf_reg2.predict(X_train)
y_pred_rf2_test = rf_reg2.predict(X_test)

train_conf_matrix_rf1 = confusion_matrix(y_train, y_pred_rf1_train)
train_prec_score_rf1 = precision_score(y_train, y_pred_rf1_train, average=None)
train_recall_score_rf1 = recall_score(y_train, y_pred_rf1_train, average=None)

train_conf_matrix_rf2 = confusion_matrix(y_train, y_pred_rf2_train)
train_prec_score_rf2 = precision_score(y_train, y_pred_rf2_train, average=None)
train_recall_score_rf2 = recall_score(y_train, y_pred_rf2_train, average=None)

test_conf_matrix_rf1 = confusion_matrix(y_test, y_pred_rf1_test)
test_prec_score_rf1 = precision_score(y_test, y_pred_rf1_test, average=None)
test_recall_score_rf1 = recall_score(y_test, y_pred_rf1_test, average=None)

test_conf_matrix_rf2 = confusion_matrix(y_test, y_pred_rf2_test)
test_prec_score_rf2 = precision_score(y_test, y_pred_rf2_test, average=None)
test_recall_score_rf2 = recall_score(y_test, y_pred_rf2_test, average=None)

print(f"{train_conf_matrix_rf1 = }")
print(f"{train_prec_score_rf1 = }")
print(f"{train_recall_score_rf1 = }")
print(f"{train_conf_matrix_rf2 = }")
print(f"{train_prec_score_rf2 = }")
print(f"{train_recall_score_rf2 = }")
print(f"{test_conf_matrix_rf1 = }")
print(f"{test_prec_score_rf1 = }")
print(f"{test_recall_score_rf1 = }")
print(f"{test_conf_matrix_rf2 = }")
print(f"{test_prec_score_rf2 = }")
print(f"{test_recall_score_rf2 = }")


train_conf_matrix_rf1 = array([[40,  0,  0],
       [ 0, 40,  0],
       [ 0,  0, 40]])
train_prec_score_rf1 = array([1., 1., 1.])
train_recall_score_rf1 = array([1., 1., 1.])
train_conf_matrix_rf2 = array([[40,  0,  0],
       [ 0, 40,  0],
       [ 0,  0, 40]])
train_prec_score_rf2 = array([1., 1., 1.])
train_recall_score_rf2 = array([1., 1., 1.])
test_conf_matrix_rf1 = array([[10,  0,  0],
       [ 0,  9,  1],
       [ 0,  1,  9]])
test_prec_score_rf1 = array([1. , 0.9, 0.9])
test_recall_score_rf1 = array([1. , 0.9, 0.9])
test_conf_matrix_rf2 = array([[10,  0,  0],
       [ 0,  9,  1],
       [ 0,  0, 10]])
test_prec_score_rf2 = array([1.        , 1.        , 0.90909091])
test_recall_score_rf2 = array([1. , 0.9, 1. ])
